name: Wetieko
description: Wetieko - Sosyal baÄŸlantÄ±lar, etkinlikler ve yeni insanlar keÅŸfet.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI ve temel kÃ¼tÃ¼phaneler
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.1.0
  flutter_riverpod: ^2.4.0

  # Konum & harita
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  apple_maps_flutter: ^1.0.0
  flutter_map: ^5.0.0
  timezone: ^0.9.2

  # Medya ve dosya iÅŸlemleri
  image_picker: ^1.0.4
  path_provider: ^2.1.3
  share_plus: ^10.0.0
  photo_view: ^0.15.0

  # AÄŸ ve izinler
  dio: ^5.4.0
  http: ^1.1.0
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.0.0
  app_links: ^6.1.3
  url_launcher: ^6.2.1
  crypto: ^3.0.3

  # GiriÅŸ / Kimlik doÄŸrulama
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0

  # GerÃ§ek zamanlÄ± iletiÅŸim
  socket_io_client: ^2.0.3+1   # âŒ YakÄ±nda kaldÄ±racaÄŸÄ±z
  signalr_netcore: 1.4.4       # âœ… EKLENDÄ° â€” SignalR iÃ§in

  # ğŸ›’ Uygulama iÃ§i satÄ±n alma
  in_app_purchase: ^3.1.9
  in_app_purchase_storekit: ^0.3.2
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^17.1.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/location_permission.png
    - assets/images/w1.png
    - assets/images/w2.png
    - assets/images/w3.png
    - assets/images/w4.png
    - assets/images/w5.png
    - assets/images/app_icon.png
    - assets/images/wetieko_logo.png
    - assets/data/sectors_professions_skills.json

# ğŸš€ Splash Screen
flutter_native_splash:
  color: "#F5F7FA"
  image: assets/images/wetieko_logo.png
  android: true
  ios: true
  fullscreen: true

# ğŸ§© Uygulama ikonu
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
