name: wetieko
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  flutter_riverpod: ^2.4.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2

  timezone: ^0.9.2
  google_maps_flutter: ^2.5.0
  flutter_map: ^5.0.0
  apple_maps_flutter: ^1.0.0
  url_launcher: ^6.2.1
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  http: ^1.1.0
  crypto: ^3.0.3
  dio: ^5.4.0
  path_provider: ^2.1.3
  app_links: ^6.1.3
  share_plus: ^10.0.0
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.0.0

  # ✅ Socket.io Client
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3   # ✅ Tek splash buradan

flutter:
  generate: true
  uses-material-design: true

  assets:
    # ✅ Görseller
    - assets/images/google_logo.png
    - assets/images/location_permission.png
    - assets/images/w1.png
    - assets/images/w2.png
    - assets/images/w3.png
    - assets/images/w4.png
    - assets/images/w5.png
    - assets/images/wetiekologo1.png

    # ✅ JSON verileri
    - assets/data/sectors_professions_skills.json

flutter_native_splash:
  color: "#F5F7FA"
  android: true
  ios: true
  fullscreen: true
